using dndCompanion.Models.Spell;
using System;
using System.Collections.Generic;
using System.Text;
using System.Threading.Tasks;
using System.Linq;

namespace dndCompanion.Services
{
    class MockDndDataStore : IDataStore<Spell>
    {
        readonly List<Spell> spells;

        public MockDndDataStore()
        {
            spells = new List<Spell>()
            {
                new Spell{Name="Acid Splash", Level=0},
                new Spell{Name="Aid", Level=2},
                new Spell{Name="Alarm", Level=1},
                new Spell{Name="Alter Self", Level=2},
                new Spell{Name="Animal Friendship", Level=1},
                new Spell{Name="Animal Messenger", Level=2},
                new Spell{Name="Animal Shapes", Level=8},
                new Spell{Name="Animate Dead", Level=3},
                new Spell{Name="Animate Objects", Level=5, Show = true},
                new Spell{Name="Antilife Shell", Level=5},
                new Spell{Name="Antimagic Field", Level=8},
                new Spell{Name="Antipathy/Sympathy", Level=8},
                new Spell{Name="Arcane Eye", Level=4},
                new Spell{Name="Arcane Gate", Level=6},
                new Spell{Name="Arcane Lock", Level=2},
                new Spell{Name="Armor of Agathys", Level=1},
                new Spell{Name="Arms of Hadar", Level=1},
                new Spell{Name="Astral Projection", Level=9},
                new Spell{Name="Augury", Level=2},
                new Spell{Name="Aura of Life", Level=4},
                new Spell{Name="Aura of Purity", Level=4},
                new Spell{Name="Aura of Vitality", Level=3},
                new Spell{Name="Awaken", Level=5},
                new Spell{Name="Bane", Level=1},
                new Spell{Name="Banishing Smite", Level=5},
                new Spell{Name="Banishment", Level=4},
                new Spell{Name="Barkskin", Level=2},
                new Spell{Name="Beacon of Hope", Level=3},
                new Spell{Name="Beast Sense", Level=2},
                new Spell{Name="Bestow Curse", Level=3},
                new Spell{Name="Bigby's Hand", Level=5},
                new Spell{Name="Blade Barrier", Level=6},
                new Spell{Name="Blade Ward", Level=0},
                new Spell{Name="Bless", Level=1},
                new Spell{Name="Blight", Level=4},
                new Spell{Name="Blinding Smite", Level=3},
                new Spell{Name="Blindness/Deafness", Level=2},
                new Spell{Name="Blink", Level=3},
                new Spell{Name="Blur", Level=2},
                new Spell{Name="Branding Smite", Level=2},
                new Spell{Name="Burning Hands", Level=1},
                new Spell{Name="Call Lightning", Level=3},
                new Spell{Name="Calm Emotions", Level=2},
                new Spell{Name="Chain Lightning", Level=6},
                new Spell{Name="Charm Person", Level=1},
                new Spell{Name="Chill Touch", Level=0},
                new Spell{Name="Chromatic Orb", Level=1},
                new Spell{Name="Circle of Death", Level=6},
                new Spell{Name="Circle of Power", Level=5},
                new Spell{Name="Clairvoyance", Level=3},
                new Spell{Name="Clone", Level=8},
                new Spell{Name="Cloud of Daggers", Level=2},
                new Spell{Name="Cloudkill", Level=5},
                new Spell{Name="Color Spray", Level=1},
                new Spell{Name="Command", Level=1},
                new Spell{Name="Commune", Level=5},
                new Spell{Name="Commune with Nature", Level=5},
                new Spell{Name="Compelled Duel", Level=1},
                new Spell{Name="Comprehend Languages", Level=1},
                new Spell{Name="Compulsion", Level=4},
                new Spell{Name="Cone of Cold", Level=5},
                new Spell{Name="Confusion", Level=4},
                new Spell{Name="Conjure Animals", Level=3},
                new Spell{Name="Conjure Barrage", Level=3},
                new Spell{Name="Conjure Celestial", Level=7},
                new Spell{Name="Conjure Elemental", Level=5},
                new Spell{Name="Conjure Fey", Level=6},
                new Spell{Name="Conjure Minor Elementals", Level=4},
                new Spell{Name="Conjure Volley", Level=5},
                new Spell{Name="Conjure Woodland Beings", Level=4},
                new Spell{Name="Contact Other Plane", Level=5},
                new Spell{Name="Contagion", Level=5},
                new Spell{Name="Contingency", Level=6},
                new Spell{Name="Continual Flame", Level=2},
                new Spell{Name="Control Water", Level=4},
                new Spell{Name="Control Weather", Level=8},
                new Spell{Name="Cordon of Arrows", Level=2},
                new Spell{Name="Counterspell", Level=3},
                new Spell{Name="Create Food and Water", Level=3},
                new Spell{Name="Create or Destroy Water", Level=1},
                new Spell{Name="Create Undead", Level=6},
                new Spell{Name="Creation", Level=5},
                new Spell{Name="Crown of Madness", Level=2},
                new Spell{Name="Crusader's Mantle", Level=3},
                new Spell{Name="Cure Wounds", Level=1},
                new Spell{Name="Dancing Lights", Level=0},
                new Spell{Name="Darkness", Level=2},
                new Spell{Name="Darkvision", Level=2},
                new Spell{Name="Daylight", Level=3},
                new Spell{Name="Death Ward", Level=4},
                new Spell{Name="Delayed Blast Fireball", Level=7},
                new Spell{Name="Demiplane", Level=8},
                new Spell{Name="Destructive Wave", Level=5},
                new Spell{Name="Detect Evil and Good", Level=1},
                new Spell{Name="Detect Magic", Level=1},
                new Spell{Name="Detect Poison and Disease", Level=1},
                new Spell{Name="Detect Thoughts", Level=2},
                new Spell{Name="Dimension Door", Level=4},
                new Spell{Name="Disguise Self", Level=1},
                new Spell{Name="Disintegrate", Level=6},
                new Spell{Name="Dispel Evil and Good", Level=5},
                new Spell{Name="Dispel Magic", Level=3},
                new Spell{Name="Dissonant Whispers", Level=1},
                new Spell{Name="Divination", Level=4},
                new Spell{Name="Divine Favor", Level=1},
                new Spell{Name="Divine Word", Level=7},
                new Spell{Name="Dominate Beast", Level=4},
                new Spell{Name="Dominate Monster", Level=8},
                new Spell{Name="Dominate Person", Level=5},
                new Spell{Name="Drawmij's Instant Summon", Level=6},
                new Spell{Name="Dream", Level=5},
                new Spell{Name="Druidcraft", Level=0},
                new Spell{Name="Earthquake", Level=8},
                new Spell{Name="Eldritch Blast", Level=0},
                new Spell{Name="Elemental Weapon", Level=3},
                new Spell{Name="Enhance Ability", Level=2},
                new Spell{Name="Enlarge/Reduce", Level=2},
                new Spell{Name="Ensnaring Strike", Level=1},
                new Spell{Name="Entangle", Level=1},
                new Spell{Name="Enthrall", Level=2},
                new Spell{Name="Etherealness", Level=7},
                new Spell{Name="Evard's Black Tentacles", Level=4},
                new Spell{Name="Expeditious Retreat", Level=1},
                new Spell{Name="Eyebite", Level=6},
                new Spell{Name="Fabricate", Level=4},
                new Spell{Name="Faerie Fire", Level=1},
                new Spell{Name="False Life", Level=1},
                new Spell{Name="Fear", Level=3},
                new Spell{Name="Feather Fall", Level=1},
                new Spell{Name="Feeblemind", Level=8},
                new Spell{Name="Feign Death", Level=3},
                new Spell{Name="Find Familiar", Level=1},
                new Spell{Name="Find Steed", Level=2},
                new Spell{Name="Find the Path", Level=6},
                new Spell{Name="Find Traps", Level=2},
                new Spell{Name="Finger of Death", Level=7},
                new Spell{Name="Fire Bolt", Level=0},
                new Spell{Name="Fire Shield", Level=4},
                new Spell{Name="Fire Storm", Level=7},
                new Spell{Name="Fireball", Level=3},
                new Spell{Name="Flame Blade", Level=2},
                new Spell{Name="Flame Strike", Level=5},
                new Spell{Name="Flaming Sphere", Level=2},
                new Spell{Name="Flesh to Stone", Level=6},
                new Spell{Name="Fly", Level=3},
                new Spell{Name="Fog Cloud", Level=1},
                new Spell{Name="Forbiddance", Level=6},
                new Spell{Name="Forcecage", Level=7},
                new Spell{Name="Foresight", Level=9},
                new Spell{Name="Freedom of Movement", Level=4},
                new Spell{Name="Friends", Level=0},
                new Spell{Name="Gaseous Form", Level=3},
                new Spell{Name="Gate", Level=9},
                new Spell{Name="Geas", Level=5},
                new Spell{Name="Gentle Repose", Level=2},
                new Spell{Name="Giant Insect", Level=4},
                new Spell{Name="Glibness", Level=8},
                new Spell{Name="Globe of Invulnerability", Level=6},
                new Spell{Name="Glyph of Warding", Level=3},
                new Spell{Name="Goodberry", Level=1},
                new Spell{Name="Grasping Vine", Level=4},
                new Spell{Name="Grease", Level=1},
                new Spell{Name="Greater Invisibility", Level=4},
                new Spell{Name="Greater Restoration", Level=5},
                new Spell{Name="Guardian of Faith", Level=4},
                new Spell{Name="Guards and Wards", Level=6},
                new Spell{Name="Guidance", Level=0},
                new Spell{Name="Guiding Bolt", Level=1},
                new Spell{Name="Gust of Wind", Level=2},
                new Spell{Name="Hail of Thorns", Level=1},
                new Spell{Name="Hallow", Level=5},
                new Spell{Name="Hallucinatory Terrain", Level=4},
                new Spell{Name="Harm", Level=6},
                new Spell{Name="Haste", Level=3},
                new Spell{Name="Heal", Level=6},
                new Spell{Name="Healing Word", Level=1},
                new Spell{Name="Heat Metal", Level=2},
                new Spell{Name="Hellish Rebuke", Level=1},
                new Spell{Name="Heroes' Feast", Level=6},
                new Spell{Name="Heroism", Level=1},
                new Spell{Name="Hex", Level=1},
                new Spell{Name="Hold Monster", Level=5},
                new Spell{Name="Hold Person", Level=2},
                new Spell{Name="Holy Aura", Level=8},
                new Spell{Name="Hunger of Hadar", Level=3},
                new Spell{Name="Hunter's Mark", Level=1},
                new Spell{Name="Hypnotic Pattern", Level=3},
                new Spell{Name="Ice Storm", Level=4},
                new Spell{Name="Identify", Level=1},
                new Spell{Name="Illusory Script", Level=1},
                new Spell{Name="Imprisonment", Level=9},
                new Spell{Name="Incendiary Cloud", Level=8},
                new Spell{Name="Inflict Wounds", Level=1},
                new Spell{Name="Insect Plague", Level=5},
                new Spell{Name="Invisibility", Level=2},
                new Spell{Name="Jump", Level=1},
                new Spell{Name="Knock", Level=2},
                new Spell{Name="Legend Lore", Level=5},
                new Spell{Name="Leomund's Secret Chest", Level=4},
                new Spell{Name="Leomund's Tiny Hut", Level=3},
                new Spell{Name="Lesser Restoration", Level=2},
                new Spell{Name="Levitate", Level=2},
                new Spell{Name="Light", Level=0},
                new Spell{Name="Lightning Arrow", Level=3},
                new Spell{Name="Lightning Bolt", Level=3},
                new Spell{Name="Locate Animals or Plants", Level=2},
                new Spell{Name="Locate Creature", Level=4},
                new Spell{Name="Locate Object", Level=2},
                new Spell{Name="Longstrider", Level=1},
                new Spell{Name="Mage Armor", Level=1},
                new Spell{Name="Mage Hand", Level=0},
                new Spell{Name="Magic Circle", Level=3},
                new Spell{Name="Magic Jar", Level=6},
                new Spell{Name="Magic Missile", Level=1},
                new Spell{Name="Magic Mouth", Level=2},
                new Spell{Name="Magic Weapon", Level=2},
                new Spell{Name="Major Image", Level=3},
                new Spell{Name="Mass Cure Wounds", Level=5},
                new Spell{Name="Mass Heal", Level=9},
                new Spell{Name="Mass Healing Word", Level=3},
                new Spell{Name="Mass Suggestion", Level=6},
                new Spell{Name="Maze", Level=8},
                new Spell{Name="Meld into Stone", Level=3},
                new Spell{Name="Melf's Acid Arrow", Level=2},
                new Spell{Name="Mending", Level=0},
                new Spell{Name="Message", Level=0},
                new Spell{Name="Meteor Swarm", Level=9},
                new Spell{Name="Mind Blank", Level=8},
                new Spell{Name="Minor Illusion", Level=0},
                new Spell{Name="Mirage Arcane", Level=7},
                new Spell{Name="Mirror Image", Level=2},
                new Spell{Name="Mislead", Level=5},
                new Spell{Name="Misty Step", Level=2},
                new Spell{Name="Modify Memory", Level=5},
                new Spell{Name="Moonbeam", Level=2},
                new Spell{Name="Mordenkainen's Faithful Hound", Level=4},
                new Spell{Name="Mordenkainen's Magnificent Mansion", Level=7},
                new Spell{Name="Mordenkainen's Private Sanctum", Level=4},
                new Spell{Name="Mordenkainen's Sword", Level=7},
                new Spell{Name="Move Earth", Level=6},
                new Spell{Name="Nondetection", Level=3},
                new Spell{Name="Nystul's Magic Aura", Level=2},
                new Spell{Name="Otiluke's Freezing Sphere", Level=6},
                new Spell{Name="Otiluke's Resilient Sphere", Level=4},
                new Spell{Name="Otto's Irresistible Dance", Level=6},
                new Spell{Name="Pass Without Trace", Level=2},
                new Spell{Name="Passwall", Level=5},
                new Spell{Name="Phantasmal Force", Level=2},
                new Spell{Name="Phantasmal Killer", Level=4},
                new Spell{Name="Phantom Steed", Level=3},
                new Spell{Name="Planar Ally", Level=6},
                new Spell{Name="Planar Binding", Level=5},
                new Spell{Name="Plane Shift", Level=7},
                new Spell{Name="Plant Growth", Level=3},
                new Spell{Name="Poison Spray", Level=0},
                new Spell{Name="Polymorph", Level=4},
                new Spell{Name="Power Word Heal", Level=9},
                new Spell{Name="Power Word Kill", Level=9},
                new Spell{Name="Power Word Stun", Level=8},
                new Spell{Name="Prayer of Healing", Level=2},
                new Spell{Name="Prestidigitation", Level=0},
                new Spell{Name="Prismatic Spray", Level=7},
                new Spell{Name="Prismatic Wall", Level=9},
                new Spell{Name="Produce Flame", Level=0},
                new Spell{Name="Programmed Illusion", Level=6},
                new Spell{Name="Project Image", Level=7},
                new Spell{Name="Protection from Energy", Level=3},
                new Spell{Name="Protection from Evil and Good", Level=1},
                new Spell{Name="Protection from Poison", Level=2},
                new Spell{Name="Purify Food and Drink", Level=1},
                new Spell{Name="Raise Dead", Level=5},
                new Spell{Name="Rary's Telepathic Bond", Level=5},
                new Spell{Name="Ray of Enfeeblement", Level=2},
                new Spell{Name="Ray of Frost", Level=0},
                new Spell{Name="Ray of Sickness", Level=1},
                new Spell{Name="Regenerate", Level=7},
                new Spell{Name="Reincarnate", Level=5},
                new Spell{Name="Remove Curse", Level=3},
                new Spell{Name="Resistance", Level=0},
                new Spell{Name="Resurrection", Level=7},
                new Spell{Name="Reverse Gravity", Level=7},
                new Spell{Name="Revivify", Level=3},
                new Spell{Name="Rope Trick", Level=2},
                new Spell{Name="Sacred Flame", Level=0},
                new Spell{Name="Sanctuary", Level=1},
                new Spell{Name="Scorching Ray", Level=2},
                new Spell{Name="Scrying", Level=5},
                new Spell{Name="Searing Smite", Level=1},
                new Spell{Name="See Invisibility", Level=2},
                new Spell{Name="Seeming", Level=5},
                new Spell{Name="Sending", Level=3},
                new Spell{Name="Sequester", Level=7},
                new Spell{Name="Shapechange", Level=9},
                new Spell{Name="Shatter", Level=2},
                new Spell{Name="Shield", Level=1},
                new Spell{Name="Shield of Faith", Level=1},
                new Spell{Name="Shillelagh", Level=0},
                new Spell{Name="Shocking Grasp", Level=0},
                new Spell{Name="Silence", Level=2},
                new Spell{Name="Silent Image", Level=1},
                new Spell{Name="Simulacrum", Level=7},
                new Spell{Name="Sleep", Level=1},
                new Spell{Name="Sleet Storm", Level=3},
                new Spell{Name="Slow", Level=3},
                new Spell{Name="Spare the Dying", Level=0},
                new Spell{Name="Speak with Animals", Level=1},
                new Spell{Name="Speak with Dead", Level=3},
                new Spell{Name="Speak with Plants", Level=3},
                new Spell{Name="Spider Climb", Level=2},
                new Spell{Name="Spike Growth", Level=2},
                new Spell{Name="Spirit Guardians", Level=3},
                new Spell{Name="Spiritual Weapon", Level=2},
                new Spell{Name="Staggering Smite", Level=4},
                new Spell{Name="Stinking Cloud", Level=3},
                new Spell{Name="Stone Shape", Level=4},
                new Spell{Name="Stoneskin", Level=4},
                new Spell{Name="Storm of Vengeance", Level=9},
                new Spell{Name="Suggestion", Level=2},
                new Spell{Name="Sunbeam", Level=6},
                new Spell{Name="Sunburst", Level=8},
                new Spell{Name="Swift Quiver", Level=5},
                new Spell{Name="Symbol", Level=7},
                new Spell{Name="Tasha's Hideous Laughter", Level=1},
                new Spell{Name="Telekinesis", Level=5},
                new Spell{Name="Telepathy", Level=8},
                new Spell{Name="Teleport", Level=7},
                new Spell{Name="Teleportation Circle", Level=5},
                new Spell{Name="Tenser's Floating Disk", Level=1},
                new Spell{Name="Thaumaturgy", Level=0},
                new Spell{Name="Thorn Whip", Level=0},
                new Spell{Name="Thunderous Smite", Level=1},
                new Spell{Name="Thunderwave", Level=1},
                new Spell{Name="Time Stop", Level=9},
                new Spell{Name="Tongues", Level=3},
                new Spell{Name="Transport via Plants", Level=6},
                new Spell{Name="Tree Stride", Level=5},
                new Spell{Name="True Polymorph", Level=9},
                new Spell{Name="True Resurrection", Level=9},
                new Spell{Name="True Seeing", Level=6},
                new Spell{Name="True Strike", Level=0},
                new Spell{Name="Tsunami", Level=8},
                new Spell{Name="Unseen Servant", Level=1},
                new Spell{Name="Vampiric Touch", Level=3},
                new Spell{Name="Vicious Mockery", Level=0},
                new Spell{Name="Wall of Fire", Level=4},
                new Spell{Name="Wall of Force", Level=5},
                new Spell{Name="Wall of Ice", Level=6},
                new Spell{Name="Wall of Stone", Level=5},
                new Spell{Name="Wall of Thorns", Level=6},
                new Spell{Name="Warding Bond", Level=2},
                new Spell{Name="Water Breathing", Level=3},
                new Spell{Name="Water Walk", Level=3},
                new Spell{Name="Web", Level=2},
                new Spell{Name="Weird", Level=9},
                new Spell{Name="Wind Walk", Level=6},
                new Spell{Name="Wind Wall", Level=3},
                new Spell{Name="Wish", Level=9},
                new Spell{Name="Witch Bolt", Level=1},
                new Spell{Name="Word of Recall", Level=6},
                new Spell{Name="Wrathful Smite", Level=1},
                new Spell{Name="Zone of Truth", Level=2
                }
            };
        }
        public async Task<bool> AddItemAsync(Spell item)
        {
            spells.Add(item);

            return await Task.FromResult(true);
        }

        public async Task<bool> DeleteItemAsync(string name)
        {
            var oldItem = spells.Where((Spell arg) => arg.Name == name).FirstOrDefault();
            spells.Remove(oldItem);

            return await Task.FromResult(true);
        }

        public async Task<Spell> GetItemAsync(string name)
        {
            return await Task.FromResult(spells.FirstOrDefault(s => s.Name == name));
        }

        public async Task<IEnumerable<Spell>> GetItemsAsync(bool forceRefresh = false)
        {
            return await Task.FromResult(spells);
        }

        public async Task<bool> UpdateItemAsync(Spell spell)
        {
            var oldItem = spells.Where((Spell arg) => arg.Name == spell.Name).FirstOrDefault();
            spells.Remove(oldItem);
            spells.Add(spell);

            return await Task.FromResult(true);
        }
    }
}
